[spring - formater z CI]
Bart3kTK/-o- pull request #4
Opened 2024-11-05 20:59 UTC by Bart3kTK

- doadanie formatera mvn
- dodanie joba z:
	- sprawdzeniem formatu
	- akutalnie z mvn test (w przyszlosci deploy)

2024-11-07 17:17 UTC, MaciejBinczarowski requested changes
Put new lines in files. I also wonder if we should trigger build and test job after style check to avoid wasting computing time

2024-11-07 17:17 UTC, MaciejBinczarowski commented on .github/workflows/spring_format_check.yml
> +      run: ./../scripts/spring/spring_format_check.sh
Put please new line at the end of file

2024-11-07 17:17 UTC, MaciejBinczarowski commented on scripts/spring/spring_format_check.sh
> +fi
new line

2024-11-07 17:17 UTC, MaciejBinczarowski commented on scripts/spring/spring_format_check.sh
> +if [ -n "$(git diff)" ]; then
dont we have single command for checking format?

2024-11-07 17:23 UTC, Bart3kTK commented on scripts/spring/spring_format_check.sh
> +if [ -n "$(git diff)" ]; then
A okazało się że ma xd

2024-11-07 17:24 UTC, Bart3kTK commented on scripts/spring/spring_format_check.sh
> +fi
🫨🫨

2024-11-07 17:24 UTC, Bart3kTK commented on .github/workflows/spring_format_check.yml
> +      run: ./../scripts/spring/spring_format_check.sh
😵‍💫🫨😵‍💫

2024-11-09 08:24 UTC, MaciejBinczarowski approved these changes

2024-11-09 08:24 UTC, MaciejBinczarowski commented on .github/workflows/spring_format_check.yml
> +      run: mvn formatter:validate
Great job!

2024-11-09 11:03 UTC, merged